//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChiefIVRScripted.rc
//
#define IDR_CHIEFITYPE_CNTR_IP          6
#define IDR_MODULE_CNTR_IP              7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_NODETREE_FORMVIEW           101
#define IDP_FAILED_TO_CREATE            102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_NODROP                      106
#define IDD_PAGE_GENERAL                106
#define IDR_MAINFRAME                   121
#define IDR_CHIEFITYPE                  122
#define IDR_MODULE                      123
#define IDB_NODE_TOOLBOX                130
#define IDB_MONO_DOCKTOOL               131
#define IDB_BITMAP1                     132
#define IDB_BITMAP3                     132
#define IDI_WAITCALL                    133
#define IDI_PLAY_START                  134
#define IDI_DIAL_START                  135
#define IDI_RELASECALL                  136
#define IDI_CALLHOLD                    137
#define IDI_TRANSFER_START              138
#define IDI_RECORD_START                139
#define IDI_SETVARIABLE                 140
#define IDI_COMPARE                     141
#define IDI_ICON1                       143
#define IDI_TREE_ROOT                   143
#define IDI_ICON2                       145
#define IDB_IMAGELIST                   146
#define IDB_IL_TAB                      147
#define IDD_NODEREMARK_FORMVIEW         149
#define IDD_VOXFILE_FORMVIEW            150
#define IDB_IB_TAB                      151
#define IDB_BIMAGELIST                  152
#define IDD_CHECK_FORMVIEW              153
#define IDD_FIND_FORMVIEW               154
#define IDC_CURSOR_MOVE                 155
#define IDC_DROP                        155
#define IDC_CURSOR_STOPMOVE             156
#define IDC_CURSOR_DRAW                 157
#define IDC_DRAW                        157
#define IDD_CLASSVIEW_FORMVIEW          159
#define IDI_START                       164
#define IDR_POP_EDIT                    167
#define IDD_PAGE_WAITCALL_SPC           168
#define IDD_PAGE_SETVARIABLE_SPC        170
#define IDD_DIALOG_ADDVAR               171
#define IDD_PAGE_PLAY_SPC               173
#define IDD_PAGE_MAKECALL_SPC           174
#define IDD_PAGE_RELEASECALL_SPC        175
#define IDD_PAGE_CALLHOLD               176
#define IDD_PAGE_TRANSFER               177
#define IDD_PAGE_CALLRECORD             178
#define IDD_PAGE_COMPARE                179
#define IDD_EDITCOMPARE_DEFINE_DLG      180
#define IDD_DIALOG_SELSECT_VAR          182
#define IDI_TRANSFER_CHECK              185
#define IDI_RECORD_STOP                 186
#define IDI_PLAY_CHECK                  187
#define IDI_DATABASE_CLOASE             188
#define IDI_DATABASE_OPEN               189
#define IDI_EXCUTE_SQL                  190
#define IDI_CONFERENCE_ENTER            191
#define IDI_CONFERENCE_LEAVE            192
#define IDI_DIAL_CHECK                  193
#define IDI_VARIABLE_DBCON              194
#define IDI_VARIABLE_DLL                195
#define IDI_VARIABLE_STR                196
#define IDI_VARIABLE_INT                197
#define IDI_VARIABLE_DBREC              198
#define IDI_VARIABLE_FLOAT              199
#define IDD_DIALOG_ADDNORMALVAR         200
#define IDD_PAGE_DBOPEN_SPC             201
#define IDI_DTMF_SEND                   202
#define IDI_DTMF_RECIVE                 203
#define IDI_DLL_LOAD                    204
#define IDI_DLL_CALL                    205
#define IDI_DLL_UNLOAD                  206
#define IDD_DIALOG_CONNECT              207
#define IDD_PAGE_MAKECALLCHECK_SPC      209
#define IDD_PAGE_PLAYCHECK              211
#define IDI_EVENT_CHECK                 213
#define IDD_PAGE_EVENTCHECK_SPC         214
#define IDD_PAGE_TRANSFER_CHECK         215
#define IDD_PAGE_CONF_ENTER_SPC         216
#define IDD_SELECT_CONSTANTVAR          218
#define IDD_PAGE_CONF_LEAVE_SPC         219
#define IDD_PAGE_CLOSEDB                220
#define IDD_PAGE_SQLEXCUTE_SPC          221
#define IDD_PAGE_DLLLOAD_SPC            223
#define IDD_PAGE_DBBROWSE_SPC           224
#define IDI_DATABASE_BROWSE             226
#define IDD_PAGE_DLLUNLOAD              228
#define IDD_PAGE_DLLCALL_SPC            229
#define IDD_PAGE_DTMFSEND_SPC           231
#define IDD_PAGE_DTMFRECIVE_SPC         232
#define IDR_TOOLBAR_SCRIPT              237
#define IDR_POPUP                       239
#define IDR_TOOLBAR_BUILD               240
#define IDI_CHECK_ERROR                 242
#define IDI_CHECK_NODE                  243
#define IDI_CHECK_WARN                  244
#define IDI_CHECK_NOTIFY                245
#define IDD_DIALOG_EXPRESS              246
#define IDI_DTMF_MENU                   247
#define IDD_PAGE_DTMFMENU_SPC           248
#define IDI_CALLLOGREQUEST              249
#define IDD_PAGE_CALLLOGREQUEST_SPC     250
#define IDD_SELECT_SYSTEMVAR            251
#define IDI_NODE_END                    254
#define IDD_PAGE_SWITCH_SPC             256
#define IDI_SWITCH                      258
#define IDI_ANSWER                      259
#define IDB_BITMAP2                     264
#define IDI_FAXRECIVE                   266
#define IDI_FAXSEND                     267
#define IDB_BITMAP_ABOUT                268
#define IDD_PAGE_SENDFAX                269
#define IDD_PAGE_FAXRECIVE              270
#define IDI_CONFER_BUILD                272
#define IDI_CONFER_DELETE               273
#define IDI_CONFER_MEMBER               275
#define IDD_PAGE_CONFER_BULID           276
#define IDD_PAGE_CONFER_DELETE          277
#define IDD_PPAGE_GETCONFMEMBER         278
#define IDI_CONFER_REQUEST              279
#define IDD_PAGE_CONFER_REQUEST         281
#define IDB_LIST_TOOL                   284
#define IDI_BLOCK                       285
#define IDI_ENTER                       286
#define IDI_RETURN                      287
#define IDI_STOREDPROC                  288
#define IDD_PPAGE_STOREPROC             289
#define IDD_PAGE_CHANGEVOICE            291
#define IDI_CHANGE_VOICE                292
#define IDI_ENDCALLEVENT_CHECK          293
#define IDI_ENDCALLEVENT_END            294
#define IDD_PAGE_TRANSFER_START         295
#define IDI_CONFER_PLAY                 297
#define IDI_CONFER_RECORD               298
#define IDI_FUNCTION                    299
#define IDI_EXPRESS                     300
#define IDD_PAGE_CONF_PLAY_SPC          301
#define IDD_PAGE_CONF_RECORD_SPC        302
#define IDD_PAGE_FUNCTION               303
#define IDD_PAGE_EXPRESS                304
#define IDI_GOTO                        311
#define IDD_DIALOG_RENAME               312
#define IDI_TRANSFER_TOCUS              313
#define IDI_ROUTECALL                   314
#define IDD_PAGE_ROUTECALL              316
#define IDD_PPAGE_CHANGE_SCRIPT         317
#define IDI_TRACE_INFO                  318
#define IDD_PPAGE_TRACE_SPC             319
#define IDD_DIALOG_DOCTYPE              320
#define IDB_START                       321
#define IDD_PAGE_MODULE                 328
#define IDI_MODULE                      329
#define IDD_MODULE_PARAM                330
#define IDD_FILE_FORMVIEW               333
#define IDI_ICON_FILEVIEW               334
#define IDI_NORMAL                      336
#define IDI_MOUDLE_BEGIN                337
#define IDI_MOUDLE_END                  338
#define IDD_PAGE_SELFDEFINENODE_SPC     339
#define IDI_CUSTOM_NODE                 340
#define IDD_DIALOG_ADDACTION            341
#define IDD_DIALOG_ADDEVENT             342
#define IDD_DIALOG_TEMPLATE             343
#define IDD_DIALOG_CUSTOM_MANAGE        344
#define IDI_CC_CALLAGENT                347
#define IDI_CC_TRANSFER                 348
#define IDD_PAGE_CC_CALLAGENT           349
#define IDD_PAGE_CC_TRANSFER            350
#define IDC_CHECK_TREE                  1000
#define IDC_FIND_LIST                   1001
#define IDC_NODE_TREE                   1002
#define IDC_REMARK_LIST                 1003
#define IDC_VOXFILE_LIST                1004
#define IDC_EDIT2                       1006
#define IDC_EDIT_FINDSTR                1006
#define IDC_EDIT_RECORDEND_DTMF         1006
#define IDC_EDIT_CANCELTRANDTMF         1006
#define IDC_SWITCH_TIMEOUT              1006
#define IDC_BUTTON1                     1007
#define IDC_COMBO1                      1008
#define IDC_BUTTON_EDIT                 1008
#define IDC_BUTTON_PLAY                 1008
#define IDC_BUTTON_FOLDER               1008
#define IDC_BUTTON_FAX                  1008
#define IDC_BUTTON_CONFMEMBER           1008
#define IDC_FINDTYPE                    1008
#define IDC_COMBO_PLAYTYPE              1008
#define IDC_BTN_END_CH                  1008
#define IDC_CLASSVIEW_TREE              1009
#define IDC_BUTTON_DEL                  1009
#define IDC_COMBO_RECORDSET             1009
#define IDC_BUTTON_FAXFOLDER            1009
#define IDC_BUTTON_LISTEN               1009
#define IDC_BUTTON_EXPRESSVALUES        1009
#define IDC_BTN_TEL                     1009
#define IDC_EDIT_NAME                   1010
#define IDC_BUTTON_PAGENUMBER           1010
#define IDC_BUTTON_SPEAKER              1010
#define IDC_BTN_WAITFILE                1010
#define IDC_CHECK_CDTMF                 1011
#define IDC_EDIT_DESCRIPTION            1011
#define IDC_COMBO_SWITCHTYPE            1011
#define IDC_BUTTON_SPEAKING             1011
#define IDC_BTN_CONNFILE                1011
#define IDC_CHECK_RCALLERID             1012
#define IDC_EDIT_PANELMSG               1012
#define IDC_BUTTON_MAX_MEMBER           1012
#define IDC_EDIT_SAVECALLERID           1013
#define IDC_BUTTON_MAX_SPEAKER          1013
#define IDC_EDIT_KEY                    1013
#define IDC_EDIT_LICENCE                1013
#define IDC_CHECK_PLAY                  1014
#define IDC_BUTTON_MAX_SPEAKING         1014
#define IDC_EDIT_ADDATION               1014
#define IDC_EDIT_VoxFile                1015
#define IDC_EDIT_WARNING                1015
#define IDC_BUTTON_FILE                 1016
#define IDC_EDIT_RINGS                  1017
#define IDC_BUTTON_SAVECALLERID         1018
#define IDC_CHECK_RCALLEDID             1019
#define IDC_BUTTON_MSG                  1019
#define IDC_EDIT_SAVECALLED             1020
#define IDC_LIST_VAR                    1020
#define IDC_BUTTON_SAVECALLED           1021
#define IDC_BUTTON_NEW                  1021
#define IDC_EDIT1                       1022
#define IDC_EDIT_DTMF                   1022
#define IDC_EDIT_TIME                   1022
#define IDC_EDIT_FILE                   1022
#define IDC_EDIT_EXPRESSION             1022
#define IDC_EDIT_VARIABLE               1022
#define IDC_EDIT_DBIDENTIFY             1022
#define IDC_EDIT_CONF_NO                1022
#define IDC_EDIT_SQL                    1022
#define IDC_EDIT_FIELD                  1022
#define IDC_EDIT_FUNCTION               1022
#define IDC_EDIT_EXPRESS                1022
#define IDC_EDIT_AIMCH                  1022
#define IDC_EDIT_FILELENGTH             1022
#define IDC_EDIT_TELEPHONE              1022
#define IDC_EDIT_CONFERNO               1022
#define IDC_EDIT_STOREPRONAME           1022
#define IDC_EDIT_ELAPSETIME             1022
#define IDC_EDIT_NEWNAME                1022
#define IDC_EDIT_BEGIN_CH               1022
#define IDC_DTMFMNU_TIMEOUT             1022
#define IDC_EDIT_MODULE_FILE            1022
#define IDC_COMBO_TYPE                  1023
#define IDC_EDIT_FOLDER                 1023
#define IDC_EDIT_HANDLE                 1023
#define IDC_EDIT_VAR                    1023
#define IDC_EDIT_EXPRESSION2            1023
#define IDC_EDIT_MEMBERCOUNT            1023
#define IDC_EDIT_MAXMEMBER              1023
#define IDC_EDIT_CHANNELINDEX           1023
#define IDC_EDIT_FILEEXPRESS            1023
#define IDC_EDIT_END_CH                 1023
#define IDC_EDIT_BEGIN_CH2              1023
#define IDC_EDIT_VALUES                 1024
#define IDC_EDIT_PHONE                  1024
#define IDC_EDIT_LISTEN_NUM             1024
#define IDC_EDIT_CONF_NO3               1024
#define IDC_EDIT_TELNUM                 1024
#define IDC_EDIT_END_CH2                1024
#define IDC_EDIT_COMPLETEDTMF           1024
#define IDC_CHECK_CLEARDTMF             1025
#define IDC_EDIT_PAGE                   1025
#define IDC_EDIT_SPEAKER                1025
#define IDC_EDIT_DESCRIPT_VAR           1025
#define IDC_CHECK_RECIVE_DTMF           1026
#define IDC_EDIT_SPEAKING               1026
#define IDC_BUTTON_DTMF                 1027
#define IDC_EDIT_MAX_MEMBER             1027
#define IDC_EDIT_PLAY                   1028
#define IDC_EDIT_MAX_SPEAKER            1028
#define IDC_EDIT_MAX_SPEAKING           1029
#define IDC_CHECK_NOTANSWER             1030
#define IDC_CHECK_AFTERRINGS            1031
#define IDC_LIST_EVENT                  1032
#define IDC_EDIT_PREFIX                 1034
#define IDC_CHECK_SAVE_DETAIL           1035
#define IDC_RADIO_HOLD1                 1039
#define IDC_RADIO_HOLD2                 1040
#define IDC_RADIO_TYPE1                 1041
#define IDC_RADIO_TYPE2                 1042
#define IDC_RADIO_TYPE3                 1043
#define IDC_RADIO_DIALTYPE1             1044
#define IDC_RADIO_DIALTYPE2             1045
#define IDC_BUTTON_EX                   1046
#define IDC_EDIT_FILENAME               1047
#define IDC_BUTTON_VARIABLE             1050
#define IDC_COMBO_TESTTYPE              1054
#define IDC_TREE_NODELIST               1061
#define IDC_BUTTON_PHONE                1062
#define IDC_CHECK_PLAYSTOP              1063
#define IDC_COMBO_ACTION                1065
#define IDC_BUTTON_SELECT               1066
#define IDC_EDIT_CHANNELNO              1067
#define IDC_BUTTON_SQL                  1067
#define IDC_BUTTON_CHINDEX              1067
#define IDC_BUTTON_FILEEXPRESS          1067
#define IDC_BUTTON_CHANNEL              1068
#define IDC_COMBO_DB                    1068
#define IDC_COMBO_CMDTYPE               1070
#define IDC_LIST_FIELDVALUES            1072
#define IDC_COMBO_BROWTYPE              1073
#define IDC_EDIT_RECSETNAME             1076
#define IDC_COMBO_DLLHANDLE             1077
#define IDC_COMBO_DLL                   1078
#define IDC_LIST_PARAMETER              1079
#define IDC_BUTTON_VAR                  1083
#define IDC_EDIT_PARMVARIABLE           1084
#define IDC_BUTTON_MAXMEMBERVAR         1084
#define IDC_BUTTON_GET                  1085
#define IDC_RADIO_EDN1                  1086
#define IDC_RADIO_EDN2                  1087
#define IDC_EDIT_COUNT                  1088
#define IDC_BUTTON_SAVE                 1089
#define IDC_EDIT_RMARK                  1094
#define IDC_BUTTON_EDITOP               1095
#define IDC_BUTTON_JIA                  1096
#define IDC_BUTTON_EVENT                1096
#define IDC_TREE_SELECT                 1097
#define IDC_BUTTON_OK                   1098
#define IDC_RADIO_REQUEST1              1099
#define IDC_RADIO_REQUEST2              1100
#define IDC_RADIO_HANDLE1               1102
#define IDC_RADIO_HANDLE2               1103
#define IDC_RADIO_AIMCHTYPE1            1109
#define IDC_RADIO_AIMCHTYPE2            1110
#define IDC_COMBO_CHTYPE                1111
#define IDC_BUTTON_AIMCH                1112
#define IDC_BUTTON_JIAN                 1113
#define IDC_RADIO_PICKUP1               1113
#define IDC_BUTTON_CHENG                1114
#define IDC_RADIO_PICKUP2               1114
#define IDC_BUTTON_CHU                  1115
#define IDC_BUTTON_STRJIA               1116
#define IDC_EDIT_HOLDDTMF               1116
#define IDC_BUTTON_DAYU                 1117
#define IDC_BUTTON_XIAOYU               1118
#define IDC_BUTTON_DAYUDENDYU           1119
#define IDC_BUTTON_XIAOYUDENGYU         1120
#define IDC_RADIO_WAITOPTION1           1120
#define IDC_BUTTON_DENGYU               1121
#define IDC_EDIT_PLAYFILE               1121
#define IDC_RADIO_WAITOPTION2           1122
#define IDC_RADIO_WAITOPTION3           1123
#define IDC_EDIT_CONSTR                 1124
#define IDC_EDIT_CONN_PLAYFILE          1124
#define IDC_BUTTON_CONN                 1125
#define IDC_BUTTON_BUILDCONN            1125
#define IDC_EDIT_IDENTIFY               1126
#define IDC_EDIT_PLAYFILE_EXPRESS       1128
#define IDC_BUTTON_PLAYFILE             1132
#define IDC_LIST_PLAY                   1133
#define IDC_RADIO_PLAYTYPE1             1134
#define IDC_RADIO_PLAYTYPE2             1135
#define IDC_BUTTON_EXPRESS              1136
#define IDC_COMBO_DIALTYPE              1137
#define IDC_RADIO_PLAYTYPE3             1138
#define IDC_EDIT_FAXFILE                1141
#define IDC_BUTTON_FAXFILE              1142
#define IDC_EDIT_EXPRESS_VALUES         1142
#define IDC_BUTTON_FLODER               1143
#define IDC_BUTTON_TEL                  1144
#define IDC_RADIO_BUILDTYPE1            1145
#define IDC_RADIO_BUILDTYPE2            1146
#define IDC_RADIO_DELETETYPE1           1147
#define IDC_RADIO_DELETETYPE2           1148
#define IDC_BUTTON_CONFNO               1149
#define IDC_EDIT_AIMTEL                 1150
#define IDC_BUTTON_DialTel              1151
#define IDC_EDIT_TIMEOUT                1153
#define IDC_EDIT_PARAMETERVALUE         1155
#define IDC_CHANGEVOICE_TYPE1           1156
#define IDC_EDIT_RETURNVALUE            1156
#define IDC_BUTTON_PARAMVALUE           1157
#define IDC_CHANGEVOICE_TYPE2           1157
#define IDC_BUTTON_RETURNVALUE          1158
#define IDC_CHECK_GETREORDSET           1159
#define IDC_RADIO_TRANSFERAIM1          1162
#define IDC_RADIO_TRANSFERAIM2          1163
#define IDC_RADIO_TRANSFERAIM3          1164
#define IDC_RADIO_TRANSFERTYPE1         1165
#define IDC_RADIO_TRANSFERTYPE2         1166
#define IDC_RADIO_TRANSFERTYPE3         1167
#define IDC_RADIO_PLAYWAY2              1169
#define IDC_RADIO_PLAYWAY1              1170
#define IDC_CHECK_LOOPPLAY              1173
#define IDC_EDIT_CONFNO                 1174
#define IDC_EDIT_FILE_EXPRESS           1182
#define IDC_BUTTON_CONFERNO             1183
#define IDC_BUTTON_FUNCTION             1184
#define IDC_EDIT_RETURNVALUES           1185
#define IDC_BUTTON_RETURN               1186
#define IDC_EDIT_CONFERNO4              1190
#define IDC_CHECK_ANSWERCALL            1191
#define IDC_BUTTON_FINDNODE             1192
#define IDC_STATIC_MATCHES              1193
#define IDC_COMBO_PLAYWAY               1198
#define IDC_COMBO_RECORDTYPE            1199
#define IDC_EDIT_SSPLAY_DTMF            1203
#define IDC_ROUTE_WAITOPTION1           1205
#define IDC_ROUTE_WAITOPTION2           1206
#define IDC_ROUTE_WAITOPTION3           1207
#define IDC_EDIT_WAIT_PLAYFILE          1208
#define IDC_BTN_BEGIN_CH                1209
#define IDC_ROUTE_CONNOPTION1           1210
#define IDC_ROUTE_CONNOPTION2           1211
#define IDC_SWITCH_GETFREECH1           1214
#define IDC_SWITCH_GETFREECH2           1215
#define IDC_DTMF_OPTION1                1215
#define IDC_DTMF_OPTION2                1216
#define IDC_RADIO_AIMCHTYPE3            1216
#define IDC_EDIT_TRACE                  1217
#define IDC_BUTTON_TRACE                1218
#define IDC_LIST_DOCTYPE                1219
#define IDC_BUTTON_MODULFILE            1221
#define IDC_TREE_FILE                   1224
#define IDC_BUTTON_ACTION               1226
#define IDC_LIST_ACTION                 1227
#define IDC_BUTTON_MENU                 1229
#define IDC_LIST_MODULEEND              1231
#define IDC_RADIO_SHOW2                 1232
#define IDC_RADIO_SHOW1                 1233
#define IDC_RADIO_SHOW3                 1234
#define IDC_COMBOBOXEX_ICO              1237
#define IDC_LIST_MANAGE                 1238
#define ID_CUSTOM_UPDATE                1239
#define ID_CUSTOM_DELETE                1240
#define IDC_STATIC_WWW                  1241
#define IDC_EDIT_AIMDN                  1242
#define IDC_CHECK_ISPLAY                1243
#define IDC_CHECK_TALKWITHAIMDN         1244
#define IDC_CHECK_TIMEOUT               1246
#define IDC_BUTTON_AIMDN                1247
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_EDIT_DELETE                  32771
#define ID_EDIT_RENAME                  32772
#define ID_EDIT_PROPERTIES              32773
#define ID_CONNECT_CONNECT              32774
#define ID_CONNECT_DISCONNECT           32775
#define ID_SCRIPT_CHECK                 32777
#define ID_SCRIPT_BUILD                 32778
#define ID_CHECK_DIAL                   32780
#define ID_CHECK_TRANSFER               32781
#define ID_ENTER_CONFERENCE             32783
#define ID_LEAVE_CONFERENCE             32784
#define ID_OPEND_DATABASE               32786
#define ID_CLOSE_DATABASE               32787
#define ID_EXCUTE_SQL                   32788
#define ID_NORMAL_VARIABLE              32791
#define ID_DATABASE_VARIABLE            32792
#define ID_DLL_HADLE                    32793
#define ID_DLL_LOAD                     32796
#define ID_DLL_UNLOAD                   32797
#define ID_DLL_CALL                     32798
#define ID_SEND_DTMFCODE                32799
#define ID_RECIVE_DTMF                  32800
#define ID_SELECT_VAR                   32802
#define ID_SELECT_FIELD                 32803
#define ID_SELECT_LOGIC_OPERATOR        32804
#define ID_SELECT_CONSTANT              32805
#define ID_SELECT_FILENAME              32806
#define ID_SELECT_FILEPATH              32807
#define ID_SELECT_FOLDER                32808
#define ID_EVENT_CHECK                  32809
#define ID_SQL_DELETE1                  32811
#define ID_SQL_INSERT1                  32813
#define ID_SQL_INSERT2                  32814
#define ID_SQL_UPDATE                   32816
#define ID_SQL_SELECT1                  32817
#define ID_SQL_SELECT2                  32818
#define ID_SQL_SELECT3                  32819
#define ID_DATABASE_BROWSE              32820
#define ID_BUTTON32839                  32839
#define ID_BUTTON32840                  32840
#define CG_ID_VIEW_OUTPUT               32841
#define ID_EXPRESSION_ASSISTANT         32847
#define ID_DTMF_MENU                    32848
#define ID_CALLLOGREQUEST               32849
#define ID_NODE_END                     32850
#define ID_SWITCH                       32851
#define ID_ANSWER                       32852
#define ID_VIEW_TOOLBOX_BAR             32853
#define ID_DBCONN_STR1                  32855
#define ID_DBCONN_STR2                  32856
#define ID_DBCONN_STR3                  32857
#define ID_DBCONN_STR4                  32858
#define ID_FAXRECIVE                    32859
#define ID_FAXSEND                      32860
#define ID_BUILD_CONFERENCE             32861
#define ID_DELETE_CONFERENCE            32862
#define ID_MEMBER_CONFERENCE            32863
#define ID_REQUEST_CONFERENCE           32864
#define ID_BLOCK                        32865
#define ID_RETURN                       32867
#define ID_STOREDPROC                   32870
#define ID_CHANGE_VOICE                 32871
#define ID_TRANSFER_START               32872
#define ID_CONFERENCE_PLAY              32874
#define ID_CONFERENCE_RECORD            32875
#define ID_FUNCTION_STR_LEFT            32880
#define ID_FUNCTION_STR_LEN             32881
#define ID_FUNCTION_STR_MID             32882
#define ID_FUNCTION_STR_RIGHT           32883
#define ID_FUNCTION                     32890
#define ID_EXPRESS                      32891
#define ID_EDIT_BLOCKOPEN               32894
#define ID_FUNCTION_SYS_GETHOLDCHNL     32897
#define ID_FUNCTION_SYS_AGENTISFREE     32898
#define ID_FUNCTION_SYS_GETFREEAGENT    32899
#define ID_GOTO                         32900
#define ID_GOTO_CONNECT                 32901
#define ID_GOTO_DISCONNECT              32902
#define ID_GOTO_SHOWCONN                32903
#define ID_DELETE_NODE                  32904
#define ID_ROUTECALL                    32905
#define ID_FUNCTION_SYS_GETLINKVAR      32907
#define ID_FUNCTION_SYS_GETLINKCHTYPE   32908
#define ID_TRACE_INFO                   32912
#define ID_MODULE                       32913
#define ID_SET_PARAMETER                32914
#define ID_MOUDLE_END                   32915
#define ID_CUSTOM_NODE                  32918
#define ID_EDIT_SAVETOTEMPLATE          32921
#define ID_CUSTOM_MANAGE                32922
#define ID_CC_CALLAGENT                 32923
#define ID_CC_TRANSFER                  32924
#define ID_NODE_TOOLBOX                 64401
#define ID_WAITCALL                     64402
#define ID_START_PLAY                   64403
#define ID_START_DIAL                   64404
#define ID_RELEASECALL                  64405
#define ID_CALLHOLD                     64406
#define ID_START_RECORD                 64408
#define ID_COMPARE                      65401
#define ID_SETVARIABLE                  65402
#define CG_ID_VIEW_WORKSPACE            65403
#define ID_NOTSELECT                    65404

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32927
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
